// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
    TypedMap,
    Entity,
    Value,
    ValueKind,
    store,
    Address,
    Bytes,
    BigInt,
    BigDecimal
  } from "@graphprotocol/graph-ts";
  
  export class ReferralRewardsEntity extends Entity {
    constructor(id: string) {
      super();
      this.set("id", Value.fromString(id));
    }
  
    save(): void {
      let id = this.get("id");
      assert(id !== null, "Cannot save ReferralRewards entity without an ID");
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save ReferralRewards entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("ReferralRewards", id.toString(), this);
    }
  
    static load(id: string): ReferralRewardsEntity | null {
      return store.get("ReferralRewards", id) as ReferralRewardsEntity | null;
    }
  
    get id(): string {
      let value = this.get("id");
      return value.toString();
    }
  
    set id(value: string) {
      this.set("id", Value.fromString(value));
    }
  
    get by(): Address {
      let value = this.get("by");
      return value.toAddress();
    }
  
    set by(value: Address) {
      this.set("by", Value.fromAddress(value));
    }

    get to(): Address {
      let value = this.get("to");
      return value.toAddress();
    }
  
    set to(value: Address) {
      this.set("to", Value.fromAddress(value));
    }
  
    get amount(): BigInt {
      let value = this.get("amount");
      return value.toBigInt();
    }
  
    set amount(value: BigInt) {
      this.set("amount", Value.fromBigInt(value));
    }
  
    get iterationDaily(): BigInt {
      let value = this.get("iterationDaily");
      return value.toBigInt();
    }
  
    set iterationDaily(value: BigInt) {
      this.set("iterationDaily", Value.fromBigInt(value));
    }
  
    get iterationWeekly(): BigInt {
      let value = this.get("iterationWeekly");
      return value.toBigInt();
    }
  
    set iterationWeekly(value: BigInt) {
      this.set("iterationWeekly", Value.fromBigInt(value));
    }
  
    get iterationMonthly(): BigInt {
      let value = this.get("iterationMonthly");
      return value.toBigInt();
    }
  
    set iterationMonthly(value: BigInt) {
      this.set("iterationMonthly", Value.fromBigInt(value));
    }
  
    get treePosition(): BigInt {
      let value = this.get("treePosition");
      return value.toBigInt();
    }
  
    set treePosition(value: BigInt) {
      this.set("treePosition", Value.fromBigInt(value));
    }
  
  }
  